services:
  mariadb:
    ports:
      - '3306:3306'
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/source:/var/lib/mysql
  php:
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: profile,debug
      PHP_XDEBUG_LOG_LEVEL: 0
      PHP_IDE_CONFIG: serverName=d4d
      PHP_XDEBUG_IDEKEY: "PHPSTORM"
      PHP_XDEBUG_START_WITH_REQUEST: trigger
      PHP_XDEBUG_TRIGGER_VALUE: "PHPSTORM"
      PHP_XDEBUG_PROFILER_OUTPUT_NAME: "cachegrind.out.%t"
# For run xdebug from CLI XDEBUG_SESSION=d4d sh -c './vendor/bin/drush scr scripts/test.php'
    volumes:
      - ./code:/var/www/html
      - ./files:/mnt/files
  nginx:
    environment:
#      NGINX_SERVER_EXTRA_CONF_FILEPATH: /etc/nginx/my.locations.conf
      NGINX_DRUPAL_ALLOW_XML_ENDPOINTS: true
#      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - ./code:/var/www/html
#      - ./my.locations.conf:/etc/nginx/my.locations.conf

#  chrome:
#    image: drupalci/webdriver-chromedriver:production
#    ulimits:
#      core:
#        soft: -1
#        hard: -1
#    ports:
#      - "4444:4444"
#      - "9515:9515"
#    entrypoint:
#      - chromedriver
#      - "--log-path=/tmp/chromedriver.log"
#      - "--verbose"
#      - "--whitelisted-ips="
