version: "3"

services:
  mariadb:
    ports:
      - '127.0.0.1:3306:3306'
  php:
#    environment:
#      PHP_XDEBUG: 1
    volumes:
      - ./:/var/www/html
  nginx:
    volumes:
      - ./:/var/www/html
