version: "3"

services:
  mariadb:
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/source:/var/lib/mysql
  php:
#    environment:
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_MODE: debug
#      PHP_IDE_CONFIG: serverName=my-ide
    volumes:
      - ./code:/var/www/html
#      - ./files:/mnt/files
  nginx:
#    environment:
#      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - ./code:/var/www/html
  traefik:
    ports:
      - '8000:80'
