version: "3"

services:
  mariadb:
    ports:
      - '3306:3306'
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/source:/var/lib/mysql
  php:
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_XDEBUG_LOG_LEVEL: 0
      PHP_IDE_CONFIG: serverName=my-ide
# For run xdebug from CLI XDEBUG_SESSION=d4d sh -c './vendor/bin/drush scr scripts/test.php'
    volumes:
      - ./code:/var/www/html
#      - ./files:/mnt/files
  nginx:
#    environment:
#      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - ./code:/var/www/html
  traefik:
    ports:
      - '8000:80'
