<?php

/**
 * @file
 * Primary module hooks for YOU_MODULE module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\filter\Render\FilteredMarkup;
use Symfony\Component\VarDumper\Cloner\VarCloner;
use Symfony\Component\VarDumper\Dumper\CliDumper;
use Symfony\Component\VarDumper\Dumper\HtmlDumper;

/**
 * Dump variable. This function integrate Symfony\VarDumper for Drupal 8.
 *
 * @param $input
 * @param null $name
 */
function vd($input, $name = NULL) {
  $cloner = new VarCloner();
  $dumper = 'cli' === PHP_SAPI ? new CliDumper() : new HtmlDumper();
  $output = fopen('php://memory', 'r+b');
  $dumper->dump($cloner->cloneVar($input), $output);
  $output = stream_get_contents($output, -1, 0);
  if ($name) {
    $output = $name . ' => ' . $output;
  }
  $output = (string) $output;
  $output = FilteredMarkup::create($output);
  \Drupal::messenger()->addMessage($output);
}
